### ISSUE TITLE
"Number of open connections" does not return to zero

### ISSUE THREAD

**Issue by kuk** [tinyproxy/tinyproxy#274]
First of all, thank you for great product. Tried a number of proxy servers, tinyproxy currently works best.

I run a cluster of instances with a single tinyproxy inside docker on each of them. Plus there is a worker instance than crawls the web via these proxies. So there is just one user for all tinyproxies — python program based on scapy library.

I monitor tinyproxy stats using calls to `tinyproxy.stats` endpoint. There is a field called "Number of open connections" that bothers me. It slowly grows with time and never goes down to zero. Even after I kill crawl process and wait more than `Timeout` seconds "Number of open connections" does not go down.

If I understand correctly when the "Number of open connections" reaches `MaxClients` tinyproxy <a href="https://github.com/tinyproxy/tinyproxy/issues/199">stops responding</a>.

Could you please help me investigate this problem. How to make "Number of open connections" go down? 

Here is my tinyproxy.conf:
```
User tinyproxy
Group tinyproxy

Port 9482

DefaultErrorFile "error.txt"
StatFile "stats.json"

LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel CONNECT

PidFile "/run/tinyproxy/tinyproxy.pid"

# https://github.com/tinyproxy/tinyproxy/issues/199#issuecomment-440703812
Timeout 60
MaxClients 500
MinSpareServers 5
MaxSpareServers 20
StartServers 10
MaxRequestsPerChild 0

ConnectPort 443

BasicAuth proxy xxxxxxxxxx

DisableViaHeader Yes
XTinyproxy No
```

Output of `tinyproxy.stats` (use custom `StatFile`) 10 minutes after crawler has stopped:
```
{
  "package": "tinyproxy",
  "version": "1.10.0",
  "opens": "252",
  "reqs": "14014",
  "badconns": "0",
  "deniedconns": "0",
  "refusedconns": "0"
}
```

`/var/log/tinyproxy/tinyproxy.log` with log level `CONNECT` is in [https://github.com/tinyproxy/tinyproxy/files/3855315/tinyproxy.log.gz](https://github.com/tinyproxy/tinyproxy/files/3855315/tinyproxy.log.gz)

**Comment by rofl0r** [comment]
my naive guess would be that your script never shuts down http connections it opens.
you can easily check by running curl with http_proxy setting to make a number of connections and then look how many open connections are reported by statshost.

**Comment by kuk** [comment]
Yes sure, it is possible that my script does not close connection. But they should be killed by tinyproxy after `Timeout` seconds right?

In my example above:
1. I run a script that makes 14014 requests, 252 connections left open. Script exits, no more requests go though tinyproxy
2. In my tinyproxy config I have `Timeout 60`. I expect that after 1 minute all 252 open connections disappear. But even after 10 minutes, all these 252 connection are still there.

Isn't it a problem? or I am missing something?

**Comment by rofl0r** [comment]
> But they should be killed by tinyproxy after Timeout seconds right?

indeed. i wasn't actually aware of that timeout setting.

> Script exits

it's odd that the connections aren't detected as closed when the process exits.
but you said you're using scapy, so maybe it's due to use of raw sockets oslt ? or maybe you have a background task that does the actual connections to the proxy.

you might want to check my threads branch (see my fork), it does handle connections differently so it's possible that it works there.

**Comment by kuk** [comment]
> but you said you're using scapy, so maybe it's due to use of raw sockets oslt ? or maybe you have a background task that does the actual connections to the proxy.

There is not background process that I am aware of. 

> you might want to check my threads branch (see my fork), it does handle connections differently so it's possible that it works there.

Ok, thank you

**Comment by rofl0r** [comment]
> Ok, thank you

did this fix the issue ?

**Comment by kuk** [comment]
Tried building and running https://github.com/rofl0r/tinyproxy/archive/threads.zip . It helped but did not fix the issue.

Before (252 `opens` after 14014 `reqs`) see https://github.com/tinyproxy/tinyproxy/issues/274#issue-523948878 

```
{
  "package": "tinyproxy",
  "version": "1.10.0",
  "opens": "252",
  "reqs": "14014",
  "badconns": "0",
  "deniedconns": "0",
  "refusedconns": "0"
}
```

After (66 `opens` after 44029 `reqs`, stopped crawl process and waited 10 minutes)

```
{
  "package": "tinyproxy",
  "version": "1.10.0",
  "opens": 66,
  "reqs": 44029,
  "badconns": 340,
  "deniedconns": 0,
  "refusedconns": 0
}
```

So number of `opens` grows slower but steal leaks. My `Dockerfile` (build and run instructions)

```
FROM ubuntu:19.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends wget unzip build-essential automake

RUN wget https://github.com/rofl0r/tinyproxy/archive/threads.zip --no-check-certificate
RUN unzip threads.zip

WORKDIR tinyproxy-threads

RUN ./autogen.sh --disable-dependency-tracking
RUN make || true
RUN make install || true

RUN groupadd tinyproxy && useradd -g tinyproxy tinyproxy

COPY error.txt error.txt
COPY stats.json stats.json
COPY tinyproxy.conf tinyproxy.conf

CMD ./src/tinyproxy -d -c tinyproxy.conf

```

`tinyproxy.conf`

```
User tinyproxy
Group tinyproxy

Port 9482

DefaultErrorFile "error.txt"
StatFile "stats.json"
StatHost "stats"

LogLevel Connect

# https://github.com/tinyproxy/tinyproxy/issues/199#issuecomment-440703812
Timeout 60
MaxClients 100

ConnectPort 443

BasicAuth proxy quVeMPdj6xmjXpu

DisableViaHeader Yes
XTinyproxy No

```

Tinyproxy log for 44029 requests is in 
[https://github.com/tinyproxy/tinyproxy/files/3877568/tinyproxy.log.gz](https://github.com/tinyproxy/tinyproxy/files/3877568/tinyproxy.log.gz)

Do you have any other suggestions what to try? How to make `opens` not to leak.

Currently I just automatically restart the whole proxy container when `opens` reaches `MaxClients`. It works ok, except that while container restarts (several seconds) client requests fail. Plus it looks dirty and a bit hard to maintain.

**Comment by rofl0r** [comment]
thanks for testing.
` "badconns": 340,` - do you have an idea where these come from ?

> Dockerfile

is your crawler process running from inside a container too ?

> stopped crawl process and waited 10 minutes)

can you still see active connections with `netstat -antl` ?

**Comment by kuk** [comment]
> thanks for testing.
> "badconns": 340, - do you have an idea where these come from ?

Not sure. Do not really understand what "badconns" mean. Can just say that sites that are being crawled are very unreliable, return errors, timeout, close connections

> is your crawler process running from inside a container too ?

No, crawler runs on another instance

> can you still see active connections with netstat -antl ?

I already removed proxy from my previous comment. Here is `netstat` output from new container. It runs tinyproxy from ubuntu 19.04 package. Not you `threads` fork. It currently has 22 `opens`, that do not go down even after I wait 10 minutes after last request. 

`tinyproxy.stats` output:
```
{
  "package": "tinyproxy",
  "version": "1.10.0",
  "opens": 22,
  "reqs": 528,
  "badconns": 0,
  "deniedconns": 0,
  "refusedconns": 0
}
```

`netstat` output:
```
netstat -antl | sort
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:9482            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9482          127.0.0.1:35476         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35480         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35484         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35488         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35492         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35496         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35500         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35504         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35510         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35514         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35518         TIME_WAIT
tcp        0      0 127.0.0.1:9482          127.0.0.1:35522         TIME_WAIT
tcp        0      0 172.17.0.2:49182        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49196        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49284        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49296        79.133.87.8:80          ESTABLISHED                                                                                            
tcp        0      0 172.17.0.2:49336        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49350        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49392        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49404        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49410        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49432        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49442        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49450        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49500        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49518        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49540        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49548        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49564        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49604        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49630        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49648        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49680        79.133.87.8:80          ESTABLISHED
tcp        0      0 172.17.0.2:49762        79.133.87.8:80          ESTABLISHED
tcp        1      0 172.17.0.2:9482         95.73.54.227:51174      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51184      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51248      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51255      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51289      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51299      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51309      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51312      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51319      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51329      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51335      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51349      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51404      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51426      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51434      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51449      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51455      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51465      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51498      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51506      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51566      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51631      CLOSE_WAIT
tcp6       0      0 :::9482                 :::*                    LISTEN
```

79.133.87.8  — site being crawled
95.73.54.227 — crawler instance

Do not really understand netstat output but yes is seems that I can see active connections

**Comment by rofl0r** [comment]
> No, crawler runs on another instance

instance means ? another container?

> Do not really understand netstat output but yes is seems that I can see active connections.

indeed. precisely 22 per ip. so as if the connection wasn't terminated due to proper close() call or implicit via process exit.

> But why is does not disappear after timout?

that's the big question...

**Comment by kuk** [comment]
> instance means ? another container?
Another machine in network

> that's the big question...
Notice that in previous comment netstat output has CLOSE_WAIT states

```
...
tcp        1      0 172.17.0.2:9482         95.73.54.227:51455      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51465      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51498      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51506      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51566      CLOSE_WAIT
tcp        1      0 172.17.0.2:9482         95.73.54.227:51631      CLOSE_WAIT
...
```

Usually I see TIME_WAIT state

```
...
tcp        0      0 172.17.0.2:9482         213.87.134.150:6821     TIME_WAIT
tcp        0      0 172.17.0.2:9482         213.87.134.150:7045     TIME_WAIT
tcp        0      0 172.17.0.2:9482         213.87.134.150:7347     ESTABLISHED
tcp        0      0 172.17.0.2:9482         213.87.134.150:7547     TIME_WAIT
tcp        0      0 172.17.0.2:9482         213.87.134.150:7636     TIME_WAIT
tcp        0      0 172.17.0.2:9482         213.87.134.150:8259     TIME_WAIT
tcp        0      0 172.17.0.2:9482         213.87.134.150:8955     TIME_WAIT
tcp        0      0 172.17.0.2:9482         213.87.134.150:9930     TIME_WAIT
```

213.87.134.150 — crawler instance

Do not know what CLOSE_WAIT and TIME_WAIT mean but it seams that if state is CLOSE_WAIT connection is never removed, if TIME_WAIT — going to be removed by timeout

**Comment by outtersg** [comment]
Same problem here (tinyproxy 1.10.0 on FreeBSD 11.2 as well as RedHat 5), with TIME_WAIT and CLOSE_WAIT connections taking all the place (so some close() call is missed after having been notified that the remote closed, or after we timed out).

I will try with master on monday at work (with "real-world" connections).

**Comment by rofl0r** [comment]
does the following patch fix the issue ?

```diff
diff --git a/src/reqs.c b/src/reqs.c
index 041fb03..859ac6b 100644
--- a/src/reqs.c
+++ b/src/reqs.c
@@ -1539,6 +1539,7 @@ void handle_connection (int fd, union sockaddr_union* addr)
         ssize_t i;
         struct conn_s *connptr;
         struct request_s *request = NULL;
+        struct timeval tv;
         hashmap_t hashofheaders = NULL;
 
         char sock_ipaddr[IP_LENGTH];
@@ -1561,6 +1562,13 @@ void handle_connection (int fd, union sockaddr_union* addr)
                 return;
         }
 
+        tv.tv_usec = 0;
+        tv.tv_sec = config->idletimeout;
+        setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, (void*) &tv, sizeof(tv));
+        tv.tv_usec = 0;
+        tv.tv_sec = config->idletimeout;
+        setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, (void*) &tv, sizeof(tv));
+
         if (connection_loops (addr))  {
                 log_message (LOG_CONN,
                              "Prevented endless loop (file descriptor %d): %s",
```

**Comment by iva3682** [comment]
no. it`s not work

**Comment by rofl0r** [comment]
> no. it`s not work

well, since it does work for me i'll go ahead and merge my proposed change. unfortunately none of the people that reported an issue tested the patch, so i guess we'll have to wait and let time tell us whether the issue is resolved.

**Comment by rofl0r** [comment]
should be fixed by the referenced commit above ^

**Comment by aluisioalves123** [comment]
Im having the same problem, a lot of opened connections. Im using the master version, what should I do?

**Comment by rofl0r** [comment]
> Im using the master version, what should I do?

decrease timeout, increase max number of connections, fix the software that doesn't close stale connections (i.e. the app(s) using the proxy)

**Comment by aluisioalves123** [comment]
> decrease timeout, increase max number of connections, fix the software that doesn't close stale connections (i.e. the app(s) using the proxy)

Decreasing timout and increasing number of connections doesnt solve the problem. I was thinking about the timeout solution or maybe doing a cron job to restart my server time to time (that doenst solve completely the problem but its ok). Why the timeout doenst close the connections?

**Comment by rofl0r** [comment]
> Why the timeout doenst close the connections?

well, it does here so i suppose the app you're using sends some sort of keep-alive packets.

**Comment by aluisioalves123** [comment]
> well, it does here so i suppose the app you're using sends some sort of keep-alive packets.
Im sending e-mails with a rails app through smtp, can you tell me what is your app? Just for reference

**Comment by rofl0r** [comment]
> can you tell me what is your app? Just for reference

anything, from webbrowser to irc client, wget, curl ...

**Comment by HelloWorldFor** [comment]
新版本解决了吗
